apiVersion: apps/v1
kind: Deployment
metadata:
  name: hue-deploy
  namespace: default
  labels:
    app: hue
spec:
  selector:
    matchLabels:
      app: hue
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: hue
    spec:
      containers:
      - name: hue
        image: thefueley/philipshue:1
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 5000
            name: hue
        env:
          - name: HUE_API
            valueFrom:
              secretKeyRef:
                name: hue-api
                key: HUE_API
                optional: false
          - name: HUE_API_KEY
            valueFrom:
              secretKeyRef:
                name: hue-api
                key: HUE_API_KEY
                optional: false
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: hue-svc
  namespace: default
  labels:
    app: hue
spec:
  ports:
    - name: http
      port: 5000
      targetPort: 5000
  selector:
    app: hue
  type: LoadBalancer